# pyproject.toml

[project]
name = "shared-core"
version = "0.1.4"
dependencies = [
    "loguru==0.7.2",
    "orjson==3.10.18",
    "tomli==2.0.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]